### ISSUE TITLE
python error on installing addon

### ISSUE THREAD

**Issue by mahdiar** [CreativeDesigner3D/home_builder_4#9]
Hi
When I install it. it shows this error:
Python: Traceback (most recent call last):
  File "/app/blender/4.2/scripts/addons_core/bl_pkg/bl_extension_ops.py", line 1388, in execute
    cmd_batch = self.exec_command_iter(is_modal)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/blender/4.2/scripts/addons_core/bl_pkg/bl_extension_ops.py", line 2452, in exec_command_iter
    self.exec_legacy(source_filepath)
  File "/app/blender/4.2/scripts/addons_core/bl_pkg/bl_extension_ops.py", line 2583, in exec_legacy
    bpy.types.PREFERENCES_OT_addon_install.execute(self, bpy.context)
  File "/app/blender/4.2/scripts/startup/bl_operators/userpref.py", line 821, in execute
    bpy.ops.preferences.addon_enable(module=mod.__name__)
  File "/app/blender/4.2/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: No module named 'home_builder_4-4'

**Comment by MrCrayon** [comment]
@mahdiar I made it work renaming the folder inside the zip file from `home_builder_4-4.0.3` to `home_builder_4-4`

**Comment by PintorMX** [comment]
Thank you @MrCrayon , that worked!
